name: Drop all packages

on:
  push:

jobs:
  remove:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/delete-package-versions@v1
      with:
        package-name: 'label-studio'
        num-old-versions-to-delete: 3
