name: Sync PR

on:
  pull_request_target:
    types: [ opened, closed, converted_to_draft, ready_for_review ]
    branches:
      - master

env:
  DOWNSTREAM_REPO_OWNER: heartex
  DOWNSTREAM_REPO: label-studio-enterprise

jobs:
  sync:
    name: "Sync"
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.0.1

      - name: Create PR
        uses: actions/github-script@v6
        id: create-pr
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const result = await github.rest.repos.createDispatchEvent({
              owner: '${{ env.DOWNSTREAM_REPO_OWNER }}',
              repo: '${{ env.DOWNSTREAM_REPO }}',
              event_type: 'upstream_repo_update',
              client_payload: {
                branch_name: '${{ github.head_ref }}',
                repo_name: '${{ github.repository }}',
                commit_sha : '${{ github.event.pull_request.head.sha }}',
                title: '${{ github.event.pull_request.title }}',
                html_url: '${{ github.event.pull_request.html_url }}',
                actor: '${{ github.actor }}',
                event_action: '${{ github.event.action }}'
              }
            });
            return result
